version: '3.4'

services:
  glossary-app:
    image: glossary-app
    build: .
    environment:
      - "NODE_ENV:production"
    ports:
      - 8000:8000
    volumes:
      - './:/app'
    stdin_open: true
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: